[package]
name = "ares"
version = "1.0.0"
description = "ARES local AI retrieval desktop app"
authors = ["Vaishnav R Menon"]
edition = "2021"

[lib]
name = "ares_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
